//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// XML document found at '\NET35.Sparkle.LinkedInNET\Services\..\..\LinkedInApi.xml'
// return types: '0'
// API groups: '1'

namespace Sparkle.LinkedInNET.Profiles
{
    using System;
    using System.Xml.Serialization;

    [Serializable]
    public class Person
    {
        /// <summary>
        /// Field: 'first-name'
        /// </summary>
        [XmlElement(ElementName = "first-name")]
        public string Firstname { get; set; }

        /// <summary>
        /// Field: 'last-name'
        /// </summary>
        [XmlElement(ElementName = "last-name")]
        public string Lastname { get; set; }

        /// <summary>
        /// Field: 'headline'
        /// Field: 'headline'
        /// </summary>
        [XmlElement(ElementName = "headline")]
        public string Headline { get; set; }

        /// <summary>
        /// Field: 'site-standard-profile-request/url'
        /// </summary>
        [XmlElement(ElementName = "site-standard-profile-request/url")]
        public string SiteStandardProfileRequestUrl { get; set; }

        /// <summary>
        /// Field: 'id'
        /// </summary>
        [XmlElement(ElementName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Field: 'maiden-name'
        /// </summary>
        [XmlElement(ElementName = "maiden-name")]
        public string MaidenName { get; set; }

        /// <summary>
        /// Field: 'formatted-name'
        /// </summary>
        [XmlElement(ElementName = "formatted-name")]
        public string FormattedName { get; set; }

        /// <summary>
        /// Field: 'phonetic-first-name'
        /// </summary>
        [XmlElement(ElementName = "phonetic-first-name")]
        public string PhoneticFirstName { get; set; }

        /// <summary>
        /// Field: 'phonetic-last-name'
        /// </summary>
        [XmlElement(ElementName = "phonetic-last-name")]
        public string PhoneticLastName { get; set; }

        /// <summary>
        /// Field: 'formatted-phonetic-name'
        /// </summary>
        [XmlElement(ElementName = "formatted-phonetic-name")]
        public string FormattedPhoneticName { get; set; }

        /// <summary>
        /// Field: 'location:(name)'
        /// Field: 'location:(country:(code))'
        /// </summary>
        [XmlElement(ElementName = "location")]
        public Location Location { get; set; }

        /// <summary>
        /// Field: 'industry'
        /// </summary>
        [XmlElement(ElementName = "industry")]
        public string Industry { get; set; }

        /// <summary>
        /// Field: 'distance'
        /// </summary>
        [XmlElement(ElementName = "distance")]
        public string Distance { get; set; }

        /// <summary>
        /// Field: 'relation-to-viewer:(distance)'
        /// Field: 'relation-to-viewer:(related-connections)'
        /// Field: 'relation-to-viewer:(connections)'
        /// </summary>
        [XmlElement(ElementName = "relation-to-viewer")]
        public RelationToViewer RelationToViewer { get; set; }

        /// <summary>
        /// Field: 'current-status'
        /// </summary>
        [XmlElement(ElementName = "current-status")]
        public string CurrentStatus { get; set; }

        /// <summary>
        /// Field: 'current-status-timestamp'
        /// </summary>
        [XmlElement(ElementName = "current-status-timestamp")]
        public string CurrentStatusTimestamp { get; set; }

        /// <summary>
        /// Field: 'current-share'
        /// </summary>
        [XmlElement(ElementName = "current-share")]
        public string CurrentShare { get; set; }

        /// <summary>
        /// Field: 'num-connections'
        /// </summary>
        [XmlElement(ElementName = "num-connections")]
        public string NumConnections { get; set; }

        /// <summary>
        /// Field: 'num-connections-capped'
        /// </summary>
        [XmlElement(ElementName = "num-connections-capped")]
        public string NumConnectionsCapped { get; set; }

        /// <summary>
        /// Field: 'summary'
        /// </summary>
        [XmlElement(ElementName = "summary")]
        public string Summary { get; set; }

        /// <summary>
        /// Field: 'specialties'
        /// </summary>
        [XmlElement(ElementName = "specialties")]
        public string Specialties { get; set; }

        /// <summary>
        /// Field: 'positions'
        /// </summary>
        [XmlElement(ElementName = "positions")]
        public string Positions { get; set; }

        /// <summary>
        /// Field: 'picture-url'
        /// </summary>
        [XmlElement(ElementName = "picture-url")]
        public string PictureUrl { get; set; }

        /// <summary>
        /// Field: 'site-standard-profile-request'
        /// </summary>
        [XmlElement(ElementName = "site-standard-profile-request")]
        public string SiteStandardProfileRequest { get; set; }

        /// <summary>
        /// Field: 'api-standard-profile-request:(url)'
        /// Field: 'api-standard-profile-request:(headers)'
        /// </summary>
        [XmlElement(ElementName = "api-standard-profile-request")]
        public ApiStandardProfileRequest ApiStandardProfileRequest { get; set; }

        /// <summary>
        /// Field: 'public-profile-url'
        /// </summary>
        [XmlElement(ElementName = "public-profile-url")]
        public string PublicProfileUrl { get; set; }

    }
}

namespace Sparkle.LinkedInNET.Profiles
{
    using System;
    using System.Xml.Serialization;

    [Serializable]
    public class Location
    {
        /// <summary>
        /// Field: 'name'
        /// </summary>
        [XmlElement(ElementName = "name")]
        public string Name { get; set; }

    }
}

namespace Sparkle.LinkedInNET.Profiles
{
    using System;
    using System.Xml.Serialization;

    [Serializable]
    public class RelationToViewer
    {
        /// <summary>
        /// Field: 'distance'
        /// </summary>
        [XmlElement(ElementName = "distance")]
        public string Distance { get; set; }

    }
}

namespace Sparkle.LinkedInNET.Profiles
{
    using System;
    using System.Xml.Serialization;

    [Serializable]
    public class ApiStandardProfileRequest
    {
        /// <summary>
        /// Field: 'url'
        /// </summary>
        [XmlElement(ElementName = "url")]
        public string Url { get; set; }

    }
}


