//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparkle.LinkedInNET.Internals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sparkle.LinkedInNET.Internals.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API returned empty/invalid error mesage (HTTP {0}).
        /// </summary>
        internal static string ApiException_ApiEmptyErrorResult {
            get {
                return ResourceManager.GetString("ApiException_ApiEmptyErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API returned an empty result.
        /// </summary>
        internal static string ApiException_ApiEmptyResult {
            get {
                return ResourceManager.GetString("ApiException_ApiEmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error ({0}) {1} at {2}.
        /// </summary>
        internal static string ApiException_ApiErrorResult {
            get {
                return ResourceManager.GetString("ApiException_ApiErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown API error (HTTP code: {0}).
        /// </summary>
        internal static string ApiException_ApiUnknownError {
            get {
                return ResourceManager.GetString("ApiException_ApiUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API replied with a unknown HTTP code: {0}..
        /// </summary>
        internal static string ApiException_ApiUnknownHttpCode {
            get {
                return ResourceManager.GetString("ApiException_ApiUnknownHttpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth2 error ({0}): {1}.
        /// </summary>
        internal static string ApiException_OAuth2ErrorResult {
            get {
                return ResourceManager.GetString("ApiException_OAuth2ErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read stream as text: {0}.
        /// </summary>
        internal static string InternalException_ReadStreamAsText {
            get {
                return ResourceManager.GetString("InternalException_ReadStreamAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create serializer for this API call: {0}.
        /// </summary>
        internal static string InternalException_SerializerCtor {
            get {
                return ResourceManager.GetString("InternalException_SerializerCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize API response: {0}.
        /// </summary>
        internal static string InternalException_SerializerDeserialize {
            get {
                return ResourceManager.GetString("InternalException_SerializerDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize API error response: {0}.
        /// </summary>
        internal static string InternalException_SerializerDeserializeError {
            get {
                return ResourceManager.GetString("InternalException_SerializerDeserializeError", resourceCulture);
            }
        }
    }
}
